### ISSUE TITLE
Add information for postdocs and technicians

### ISSUE THREAD

**Issue by daramf** [scheuerell-lab/lab-book#14]
Suggested addition: Post-docs and technicians should investigate the options available from the insurance provider you selected when you signed up for UW Benefits.  For example, through Regence you have access to a free service called Quartet, which helps you find a therapist based on your particular concern, and will also help you change therapists until you find the right fit.

**Comment by mdscheuerell** [comment]
This has been addressed [here](https://github.com/scheuerell-lab/lab-book/blob/71e6ac089fe24c568f30dafa822b456f8210f311/health.Rmd#L37-L39).
