### ISSUE TITLE
Add section for conversation norms

### ISSUE THREAD

**Issue by mdscheuerell** [scheuerell-lab/lab-book#4]
To be based upon the list we started [here](https://docs.google.com/document/d/1m78cHhDd6mX1DGtszd-WvltQmyTsUsO56yTnJKEWuP0/edit).

**Comment by daramf** [comment]
I left comments in the linked document in the open issue. I didn't have too much to add in this first look. I did suggest some draft wording that could be included and edited.

**Comment by mdscheuerell** [comment]
Thanks @daramf!

**Comment by mdscheuerell** [comment]
I've incorporated the list that we started with in lab mtg and @daramf mentioned above into the lab manual [here](https://scheuerell-lab.github.io/lab-book/communication.html#conversation-norms).

In the future, we may want to expand the list to be more specific for certain groups/situations.
